/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.proxys;

import cn.proxys.impl.UrlsWork;
import cn.proxys.utils.Threads;

import java.util.ArrayList;
import java.util.List;

public class Main {


    private static volatile List<String> proxys=new ArrayList<String>();

    public static void main(String[] args) {
        UrlsWork.pull();
        Threads.waitForAsyncTask();
        System.out.println("所有任务结束");

    }

    public static synchronized void addResult(String ip, int port) {
        addResult(ip+":"+port);
    }
    public static synchronized void addResult(String ip, String port) {
        addResult(ip+":"+port);
    }
    public static void addResult(String proxy) {
    }


}

