name: JavaCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with maven
      run: |
        chmod -R 777 *
        git config core.filemode false
        mvn compile assembly:single
        mv `ls target/*.jar` ts.jar
        echo "============拷贝成功============"
        ls
        java -jar ts.jar ${{ secrets.GTOKEN }}
        

        
